version: "3"
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  db:
    image: "microsoft/mssql-server-linux:2017-CU8"
    environment:
      SA_PASSWORD: "My_Database_Password_1"
      ACCEPT_EULA: "Y"